//* Login
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const LIMPIAR_USER = 'LIMPIAR_USER'
export const NO_EXISTE_USER = "NO_EXISTE_USER"

//* Inventario
export const MOSTRAR_INVENTARIOS = 'MOSTRAR_INVENTARIOS'
export const MOSTRAR_INVENTARIO_UNICO = 'MOSTRAR_INVENTARIO_UNICO'
export const AGREGAR_INVENTARIO = 'AGREGAR_INVENTARIO'
export const EDITAR_INVENTARIO = 'EDITAR_INVENTARIO'
export const ELIMINAR_INVENTARIO = 'ELIMINAR_INVENTARIO'
export const LIMPIAR_INVENTARIO = 'LIMPIAR_INVENTARIO'
export const ERROR_INVENTARIO = 'ERROR_INVENTARIO'

//* Productos 
export const MOSTRAR_PRODUCTOS = "MOSTRAR_PRODUCTOS"
export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const ERROR_PRODUCTO = "ERROR_PRODUCTO";
export const LIMPIAR_PRODUCTOS = "LIMPIAR_PRODUCTOS"
export const ACTUALIZAR_PRODUCTO = "ACTUALIZAR_PRODUCTO";
export const MOSTRAR_PRODUCTO_UNICO = "MOSTRAR_PRODUCTO_UNICO";
export const ELIMINAR_PRODUCTOS = "ELIMINAR_PRODUCTOS";

//* Distribuidores
export const VER_DISTRIBUIDORES_SUCCESS = "VER_DISTRIBUIDORES_SUCCESS";
export const VER_PRODUCTOS_POR_DISTRIBUIDORES = "VER_PRODUCTOS_POR_DISTRIBUIDORES"
export const ERROR_PRODUCTOS_POR_DISTRIBUIDORES = "ERROR_PRODUCTOS_POR_DISTRIBUIDORES"
export const LIMPIAR_DISTRIBUIDORES = "LIMPIAR_DISTRIBUIDORES"

//* Cronograma
export const VER_CRONOGRAMA = "VER_CRONOGRAMA";
export const VER_CRONOGRAMA_UNICO = "VER_CRONOGRAMA_UNICO"
export const ACTUALIZAR_CRONOGRAMA = "ACTUALIZAR_CRONOGRAMA"
export const ERROR_CRONOGRAMA = "ERROR_CRONOGRAMA"
export const LIMPIAR_CRONOGRAMA = "LIMPIAR_CRONOGRAMA"

//* Puntos
export const MOSTRAR_PUNTOS = "MOSTRAR_PUNTOS";
export const LIMPIAR_PUNTOS = "LIMPIAR_PUNTOS";
export const FETCH_REGISTROPUNTOS_SUCCESS = "FETCH_REGISTROPUNTOS_SUCCESS";
export const ERROR_PUNTO = "ERROR_PUNTO";
export const ACTUALIZAR_PUNTO = "ACTUALIZAR_PUNTO";
export const MOSTRAR_PUNTO_UNICO = "MOSTRAR_PUNTO_UNICO";
export const ELIMINAR_PUNTOS = "ELIMINAR_PUNTOS";
export const AGREGAR_PUNTO = "AGREGAR_PUNTO";

//* Parte Del Dia
export const MOSTRAR_PARTES_DIAS = "MOSTRAR_PARTES_DIAS";
export const LIMPIAR_PARTES_DIAS = "LIMPIAR__PARTES_DIAS";
export const AGREGAR_PARTE_DIA = "AGREGAR_PARTE_DIA";
export const ERROR_PARTE_DIA = "ERROR_PARTE_DIA";
export const ACTUALIZAR_PARTE_DIA = "ACTUALIZAR_PARTE_DIA";
export const MOSTRAR_PARTE_DIA_UNICO = "MOSTRAR_PARTE_DIA_UNICO";
export const MOSTRAR_PARTES_DIAS_POR_FECHA = "MOSTRAR_PARTES_DIAS_POR_FECHA";
export const ERROR_PARTES_DIAS_POR_FECHA = "ERROR_PARTES_DIAS_POR_FECHA";

//* Notificaciones
export const MOSTRAR_NOTIFICACIONES = "MOSTRAR_NOTIFICACIONES"
export const CAMBIAR_ESTADO_NOTIFICACION = "CAMBIAR_ESTADO_NOTIFICACION"
export const LIMPIAR_NOTIFICACIONES = "LIMPIAR_NOTIFICACIONES"
export const ERROR_NOTIFIACIONES = "ERROR_NOTIFICACIONES"

//* Noticias 
export const MOSTRAR_NOTICIAS = "MOSTRAR_NOTICIAS"
export const AGREGAR_NOTICIA = "AGREGAR_NOTICIA";
export const ERROR_NOTICIA = "ERROR_NOTICIA";
export const LIMPIAR_NOTICIAS = "LIMPIAR_NOTICIAS"
export const ACTUALIZAR_NOTICIA = "ACTUALIZAR_NOTICIA";
export const MOSTRAR_NOTICIA_UNICA = "MOSTRAR_NOTICIA_UNICA";
export const ELIMINAR_NOTICIA = "ELIMINAR_NOTICIA";


//* Noticias Nutricion
export const MOSTRAR_NUTRI_NOTICIAS = "MOSTRAR_NUTRI_NOTICIAS"
export const AGREGAR_NUTRI_NOTICIAS = "";
export const ERROR_NUTRI_NOTICIAS = "ERROR_NUTRI_NOTICIAS";
export const LIMPIAR_NUTRI_NOTICIAS = "LIMPIAR_NUTRI_NOTICIAS"
export const ACTUALIZAR_NUTRI_NOTICIAS = "ACTUALIZAR_NUTRI_NOTICIAS";
export const MOSTRAR_NUTRI_NOTICIA_UNICA = "MOSTRAR_NUTRI_NOTICIA_UNICA";
export const ELIMINAR_NUTRI_NOTICIAS = "ELIMINAR_NUTRI_NOTICIAS";


//* Programas (NetamenteFormoseño) 
export const MOSTRAR_PROGRAMAS = "MOSTRAR_PROGRAMAS"
export const AGREGAR_PROGRAMA = "AGREGAR_PROGRAMA";
export const ERROR_PROGRAMA = "ERROR_PROGRAMA";
export const LIMPIAR_PROGRAMAS = "LIMPIAR_PROGRAMAS"
export const ACTUALIZAR_PROGRAMA = "ACTUALIZAR_PROGRAMA";
export const MOSTRAR_PROGRAMA_UNICO = "MOSTRAR_PROGRAMA_UNICO";
export const ELIMINAR_PROGRAMA = "ELIMINAR_PROGRAMA";

//* Asistencias
export const MOSTRAR_CONVOCADOS = "MOSTRAR_CONVOCADOS"
export const AGREGAR_ASISTENCIA = "AGREGAR_ASISTENCIA";
export const ERROR_ASISTENCIA = "ERROR_ASISTENCIA";
export const LIMPIAR_ASISTENCIAS = "LIMPIAR_ASISTENCIAS"
export const ACTUALIZAR_ASISTENCIA = "ACTUALIZAR_ASISTENCIA";
export const MOSTRAR_ASISTENCIA_UNICA = "MOSTRAR_ASISTENCIA_UNICA";

export const AGREGAR_CONVOCADO = "AGREGAR_CONVOCADO";
export const ERROR_CONVOCADO = "ERROR_CONVOCADO";
export const LIMPIAR_CONVOCADOS = "LIMPIAR_CONVOCADOS"
export const ACTUALIZAR_CONVOCADO = "ACTUALIZAR_CONVOCADO";
